### ISSUE TITLE
Squiki down?

### ISSUE THREAD

**Issue by roiLeo** [kodadot/workers#127]
- https://squiki.kodadot.workers.dev/list
- https://squiki.kodadot.workers.dev/status/rubick
- https://squiki.kodadot.workers.dev/status/snekk

**Comment by vikiival** [comment]
Thank you for ping, I needed to update the SubSquid API KEY

![Screenshot 2023-07-20 at 12 34 22](https://github.com/kodadot/workers/assets/22471030/50feeefc-0266-4e6e-82ed-47ecb0ea770a)
