### ISSUE TITLE
Return 200 empty response on KV

### ISSUE THREAD

**Issue by Jarsen136** [kodadot/workers#143]
> > > displays proper message now: (key not found) ✔️ ![image](https://user-images.githubusercontent.com/36627808/263261095-b91cd35f-8ff4-4ce4-9abb-5bd110ab0728.png)
> > 
> > 
> > Not related to this PR. It also happened on canary env. https://canary.kodadot.xyz/ahp/gallery/1-15
> 
> i was not talking about the error message itself, just that you've fixed it and it display the error correctly

The error message comes from an api response.

`https://keywise.kodadot.workers.dev/resolve/ahp-0` Something wrong happens on the worker side.
<img width="315" alt="image" src="https://github.com/kodadot/nft-gallery/assets/31397967/b826370b-d261-4af0-b2d0-45a196cb49ee">

**Comment by vikiival** [comment]
What should be output? 
200 and empty key?

**Comment by vikiival** [comment]
Cc @prury @Jarsen136
