### ISSUE TITLE
wrong content-type when put it to r2 on image-workers

### ISSUE THREAD

**Issue by preschian** [kodadot/workers#145]
> The format of metadata is text instead of json, which is why the image could not load properly before.
> https://image-beta.w.kodadot.xyz/ipfs/bafkreiduhiiovev346oqlhnmovxzsjwjhh2g5blxoxxnmqsfxttwxgnp6a

cc @preschian 👀

_Originally posted by @vikiival in https://github.com/kodadot/nft-gallery/issues/6664#issuecomment-1703821629_

**Comment by preschian** [comment]
content-type should be JSON instead of text

![Screenshot 2023-09-04 140601](https://github.com/kodadot/workers/assets/734428/5b139d11-d8a5-4486-b872-a5d3b0eecf38)

**Comment by preschian** [comment]
I will try to delete the file on r2 and trigger it again to test it

![image](https://github.com/kodadot/workers/assets/734428/a79487b4-79b9-497a-9e51-a50785566b03)

**Comment by vikiival** [comment]
Closed by #146 ?

**Comment by preschian** [comment]
> Closed by #146 ?

yes2

for query parameters I create a new issue here https://github.com/kodadot/workers/issues/147
