### ISSUE TITLE
transform url (query params) to compatible with r2 and cfi

### ISSUE THREAD

**Issue by preschian** [kodadot/workers#147]
@preschian looks like I still get text/plain

```
https://image-beta.w.kodadot.xyz/ipfs/QmebKrkUNabQq1Yhp1QrK2EUPbUctrphu9xEmiz23bQDgM?fxhash=oouRoBFwwjEccFn6NzGso2mYXG2Pe4xaaKAkgs6ZhecKupC9HvR
```
```
text/plain;charset=UTF-8
```

_Originally posted by @vikiival in https://github.com/kodadot/workers/issues/145#issuecomment-1705252059_

**Comment by preschian** [comment]
> ```
>           @preschian looks like I still get text/plain
> ```
> 
> ```
> https://image-beta.w.kodadot.xyz/ipfs/QmebKrkUNabQq1Yhp1QrK2EUPbUctrphu9xEmiz23bQDgM?fxhash=oouRoBFwwjEccFn6NzGso2mYXG2Pe4xaaKAkgs6ZhecKupC9HvR
> ```

Is this from https://www.fxhash.xyz/?
Currently, r2 or cfi does not support paths by query parameters. `?fxhash=` need to transform this first

similar to my draft PR about custom URL here: https://github.com/kodadot/workers/pull/136/files#diff-e1e7c7d750071115b68642399da869acb766343638006008dca6ce6b1bc86f97R14
need to transform `https://www.fxhash.xyz/articles` to `https---www-fxhash-xyz-articles` first to able to put that in r2 or cfi. The results would be something like this

![image](https://github.com/kodadot/workers/assets/734428/8f789410-7f8f-4b87-8182-a5030a6399d0)

**Comment by vikiival** [comment]
> Is this from https://www.fxhash.xyz/?

Yes, playing with genArt and doing compatibility layer 

> Currently, r2 or cfi does not support paths by query parameters. ?fxhash= need to transform this first

Or I would forward that to gateway, or use fxhash gateway if `?fxhash=` parameter is present

Out of context: this is how metadata looks like (the reason I wrote kodadot/packages/hyperadata)
```
https://gateway.fxhash2.xyz/ipfs/Qma9N5nX28T9eK8hekR24inJbwgD7vZNAicbNQjYMYfntw
```

**Comment by vikiival** [comment]
> need to transform https://www.fxhash.xyz/articles to https---www-fxhash-xyz-articles first to able to put that in r2 or cfi. The results would be something like this

Why? any gatweway can read that

```
nftstorage.link/ipfs/QmebKrkUNabQq1Yhp1QrK2EUPbUctrphu9xEmiz23bQDgM?fxhash=oouRoBFwwjEccFn6NzGso2mYXG2Pe4xaaKAkgs6ZhecKupC9HvR
```

@preschian got Idea 

let's store the content without query param and after that if query params are present we will concat it to the result
And from R2 we will directly expose it :)

**Comment by preschian** [comment]
> Why? any gatweway can read that

Because we store raw content in r2 and optimized images on cfi. To see why it needs to transform before putting it to r2/cfi. You can try comparing these commands

```bash
mkdir -p nftstorage.link/ipfs/QmebKrkUNabQq1Yhp1QrK2EUPbUctrphu9xEmiz23bQDgM?fxhash=oouRoBFwwjEccFn6NzGso2mYXG2Pe4xaaKAkgs6ZhecKupC9HvR
find . -type d
```

with this

```bash
mkdir -p nftstorage.link/ipfs/QmebKrkUNabQq1Yhp1QrK2EUPbUctrphu9xEmiz23bQDgM
find . -type d
```

or with this

```bash
rm -rf nftstorage.link
mkdir -p nftstorage.link/ipfs/QmebKrkUNabQq1Yhp1QrK2EUPbUctrphu9xEmiz23bQDgM-fxhash-oouRoBFwwjEccFn6NzGso2mYXG2Pe4xaaKAkgs6ZhecKupC9HvR
find . -type d
```

Transforming it to be path-friendly is better, in my opinion, because the transformation is only on our side. and we can use the same transformation for non-ipfs paths (custom URL case). In the client, the user still hits the same URL, `gw.com/ipfs/cid?query=params`
