### ISSUE TITLE
Unify metadata on image worker

### ISSUE THREAD

**Issue by vikiival** [kodadot/workers#155]
1. install [hyperdata](https://www.npmjs.com/package/@kodadot1/hyperdata)
2. when content is application/json do normalization
3. save to R2 (as it is now)

**Comment by vikiival** [comment]
@preschian thinking what if we store JSON metadata somewhere else? like KV or D1 ?

**Comment by preschian** [comment]
@vikiival oh yes, I'm thinking like this also if we put that in our workers. ref: https://github.com/kodadot/workers/issues/95

create a new endpoint, something like `image-w.com/metadata/cid`
if the content non-json, redirect it to our normal image workers to `image-w.com/ipfs/cid`
else return our predefined structure, something like this:

```js
{
  media: '', // img/3d/audio/video
  thumbnail: '', // future research if the media non-image. is it possible or not to create a thumbnail from that in workers. ref: https://github.com/kodadot/nft-gallery/issues/6050
  mimeType: '',
  raw: {
    ...,
    // keep original metadata from ipfs here
    ...,
  }
}
```

**Comment by vikiival** [comment]
> media

Should I rename `animationUrl` to Media?
