### ISSUE TITLE
Some images are not loading on AssetHubs - IPFS Error

### ISSUE THREAD

**Issue by prury** [kodadot/workers#158]
### What happened?

First playwright detection 👍 
https://canary.kodadot.xyz/ahk/gallery/6-10
https://canary.kodadot.xyz/ahp/collection/12
https://canary.kodadot.xyz/ahk/collection/169

### Relevant log output

```shell
IPFS Err FetchError: [GET] "https://image-beta.w.kodadot.xyz/ipfs/bafkreid4bdjteh7glaznre7u6obwvckon7lbgtyj4yqs5wyoftiwzdubhm": 500 
    NuxtJS 8
c6a690c.js:49:83549
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by roiLeo** [comment]
All images on `/ahk/drops` are not loading (error 500) while it load well on beta

**Comment by yangwao** [comment]
- https://github.com/kodadot/nft-gallery/issues/7431

**Comment by yangwao** [comment]
I see CF had some issues in past -  https://www.cloudflarestatus.com/

**Comment by yangwao** [comment]
@preschian probably to do some revert?

**Comment by yangwao** [comment]
The weird thing is that on the URL I'm getting 500 - Internal Server Error, on second time I get content.
https://image-beta.w.kodadot.xyz/ipfs/QmRmjYQrKABoyEjbU9DQZrUF52UdPKcRiJkb22sbSiAU7u
![image](https://github.com/kodadot/workers/assets/5887929/42bc99b6-2305-4652-85f0-8e68b71c8d3c)

**Comment by vikiival** [comment]
> The weird thing is that on the URL I'm getting 500 - Internal Server Error, on second time I get content.

Basically any page calls makes 1000 requests on image gw. After a while it crashes

https://github.com/kodadot/nft-gallery/pull/7433#issuecomment-1742064367

**Comment by preschian** [comment]
checking

**Comment by preschian** [comment]
it seems like there is some API change from the Cloudflare worker cache. I'm not able to use this anymore `c.executionCtx.waitUntil(cache.put(cacheKey, response.clone()));`. I will disable that at the moment. And deploy this: https://github.com/kodadot/workers/pull/162
