### ISSUE TITLE
Cloudflare GW cannot process text/html

### ISSUE THREAD

**Issue by vikiival** [kodadot/workers#164]
[**image.w.kodadot.xyz**](https://image.w.kodadot.xyz/ipfs/bafybeihgypqjpdmx3yb57tbqhrnfn67ujciqp7pd3skpfdnxprqusgaoze)

<img width="1792" alt="Screenshot 2023-10-03 at 13 37 14" src="https://github.com/kodadot/workers/assets/22471030/e27e85e6-3e8f-47db-830e-2e1fb507e398">

[**nftstorage.link**](https://bafybeihgypqjpdmx3yb57tbqhrnfn67ujciqp7pd3skpfdnxprqusgaoze.ipfs.nftstorage.link/)

<img width="1792" alt="Screenshot 2023-10-03 at 13 37 31" src="https://github.com/kodadot/workers/assets/22471030/ddd2975f-505c-444e-88a7-48132a8981b7">

cc @preschian

**Comment by preschian** [comment]
noted

image workers failed to resolve the assets -> `https://cloudflare-ipfs.com/ipfs/p5.js`
should be `https://cloudflare-ipfs.com/ipfs/bafybeihgypqjpdmx3yb57tbqhrnfn67ujciqp7pd3skpfdnxprqusgaoze/p5.js`

**Comment by vikiival** [comment]
Updated code with relative paths

https://image.w.kodadot.xyz/ipfs/bafybeiau53zl3gfhcmnplmafmfwr7ryx237klgzwu6mp6ug7fat333ihqe

<img width="923" alt="Screenshot 2023-10-03 at 13 59 01" src="https://github.com/kodadot/workers/assets/22471030/329f29dd-6adb-465e-a7e3-68faac6a2b47">

https://bafybeiau53zl3gfhcmnplmafmfwr7ryx237klgzwu6mp6ug7fat333ihqe.ipfs.nftstorage.link

<img width="3120" alt="Screenshot 2023-10-03 at 13 59 15" src="https://github.com/kodadot/workers/assets/22471030/522c488f-fe0d-4310-8e5e-da2c0aaa899a">

**Comment by vikiival** [comment]
https://explore.ipld.io/#/explore/bafybeiau53zl3gfhcmnplmafmfwr7ryx237klgzwu6mp6ug7fat333ihqe

**Comment by preschian** [comment]
looks ok:
- https://image-beta.w.kodadot.xyz/ipfs/bafybeiau53zl3gfhcmnplmafmfwr7ryx237klgzwu6mp6ug7fat333ihqe
- https://image-beta.w.kodadot.xyz/ipfs/bafybeihgypqjpdmx3yb57tbqhrnfn67ujciqp7pd3skpfdnxprqusgaoze
