### ISSUE TITLE
Capture service

### ISSUE THREAD

**Issue by vikiival** [kodadot/workers#169]
### Context

When user makes and iteration (new art) there is no way on frontend to take the static image. 

The idea is to create some headless browser, capture the screen and return the image.
Ideally use `hono`.

### Original

When a generative art is renered we need to create a medata for the nft namely: `image` and `thumbnail`

This is on generative platforms like fxhash done via [Capture Settings](https://www.fxhash.xyz/doc/artist/project-settings#capture-settings)

**Comment by vikiival** [comment]
Fast hacking hour

- https://developers.cloudflare.com/browser-rendering/

1. Create worker
2. install hono
3. create route that either takes url as query param or body param
4. copy paste code https://developers.cloudflare.com/browser-rendering/get-started/screenshots/ (PLS think 🧠 )
5. return image as in the snippet above

**Comment by yangwao** [comment]
Does anyone from @kodadot/internal-dev want to take on this?

**Comment by daiagi** [comment]
Is this worker to live in workers repo?
What cloudflare account should be used?

**Comment by vikiival** [comment]
> Is this worker to live in workers repo?

Yes

> What cloudflare account should be used?

Feel free to use yours for testing     
I can setup the prod deploy then

**Comment by vikiival** [comment]
Done
