### ISSUE TITLE
Worker to proxy the beehiiv request

### ISSUE THREAD

**Issue by hassnian** [kodadot/workers#179]
> @roiLeo seems we need a server from a server , do we have a sever or something to run this ?
> 
> https://support.beehiiv.com/hc/en-us/articles/12428276693015-Why-am-I-getting-a-CORS-error-when-trying-to-implement-my-form-
> 

Look like you need a new worker to proxy the beehiiv request. If so, you could create an issue on https://github.com/kodadot/workers

ref https://stackoverflow.com/questions/73652409/fetch-request-is-being-being-blocked-by-cors-policy

_Originally posted by @Jarsen136 in https://github.com/kodadot/nft-gallery/issues/7589#issuecomment-1759171235_

**Comment by vikiival** [comment]
Newsletter worker was deployed
