### ISSUE TITLE
update the cors header

### ISSUE THREAD

**Issue by Jarsen136** [kodadot/workers#181]
> Drops do not load for me in this deployed version

Could you please update the cors header for all the `--koda-canary.netlify.app` env? 

![image](https://github.com/kodadot/nft-gallery/assets/31397967/5cd1c140-6dc6-4903-81ec-0e2e2e4a03b0)

_Originally posted by @Jarsen136 in https://github.com/kodadot/nft-gallery/issues/7634#issuecomment-1761702984_

cc @preschian

**Comment by preschian** [comment]
@Jarsen136 @vikiival which one is the waifu service?
