### ISSUE TITLE
Ahp video collection not loading

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/workers#187]
Collection video files: https://kodadot.xyz/ahp/gallery/10-26 are not loading properly. Prouduction - ahp. 

Kodachains are video files (maybe gif).

It looks like this:
![image](https://github.com/kodadot/nft-gallery/assets/104380776/69c20081-407c-40df-9b44-81f29e01372e)

**Comment by preschian** [comment]
This one seems like a worker issue, not works only on mobile devices

**Comment by preschian** [comment]
android looks fine

but, tried on ios with different gateway still fails

![image](https://github.com/kodadot/workers/assets/734428/d3c659c0-af23-4606-bb7b-4349819b6036)
