### ISSUE TITLE
Collective worker

### ISSUE THREAD

**Issue by vikiival** [kodadot/workers#189]
### Context

We can help artists onboard w/o having $DOT at their wallets, buying $DOT or teleporting assets.
The idea is to have a minter worker that can allow users to mint into a common collection, that would be managed by kodabot

### Task

1. Create a D1 storage with table `collective_items`

```sql
CREATE TABLE collective_items (
    id         TEXT PRIMARY KEY NOT NULL,
    chain      TEXT NOT NULL,
    collection TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    issuer     TEXT NOT NULL,
    metadata   TEXT NOT NULL,
    sn         INTEGER KEY AUTOINCREMENT NOT NULL,
    signature  TEXT NOT NULL,
    approved   INTEGER DEFAULT 0,
    mail       TEXT,
    hash.      TEXT
)
```

2. create REST API on routes `/collectives`

2.1 create insert into collective_items

basically `POST /collectives`

with all the data except approved and id 

id is generated as: `${chain}-${collection}-${id}`

2.2 mark collective item as approved

- this should call the minter 
- and send mail (we have service for that) 
- mark collective item as appoved and insert hash = txhash (that is the response from the minter)

### Tech stack 

TS+HONO (preffered)

REF: 
- https://github.com/kodadot/nft-gallery/issues/7825

**Comment by vikiival** [comment]
## Additional task

### Context

we would like to know who is allowed to mint in the collective collection.

### Task

1. Create a D1 storage with table `collective_approvals`

```sql
-- to be described
```

2. when someone wants to call `POST /collectives`

check if the person is allowed to mint in particular collectives

if not return `401`

**Comment by daiagi** [comment]
closing this and continue in
https://github.com/kodadot/private-workers/issues/1

**Comment by vikiival** [comment]
Transferred to kodadot/private-workers#1
