### ISSUE TITLE
e-mail subscribing on landing page not working

### ISSUE THREAD

**Issue by prury** [kodadot/workers#191]
### What happened?

![image](https://github.com/kodadot/nft-gallery/assets/36627808/cab77b04-4238-428d-b60f-5674148cdafb)

**Comment by roiLeo** [comment]
Response 401 from beehiv api, might need to throw error message when it's happening

**Comment by vikiival** [comment]
@kodadot/internal can I get an API key for beehiv?
Send pls do TG DM

**Comment by helloitsdamsky** [comment]
<img width="936" alt="image" src="https://github.com/kodadot/workers/assets/92786519/05508aab-dd82-4dd5-9777-e9a67b919213">
 cc @yangwao

**Comment by helloitsdamsky** [comment]
Let’s hide the signup component?

**Comment by roiLeo** [comment]
Have you considered another alternative? like mailchimp

**Comment by helloitsdamsky** [comment]
> Have you considered another alternative? like mailchimp

We’ve chosen beehiiv for various reasons, primarily for all-in-one platform

**Comment by helloitsdamsky** [comment]
It should be fixed within 2-3 hours, will hit you up @vikiival

**Comment by helloitsdamsky** [comment]
<img width="357" alt="image" src="https://github.com/kodadot/workers/assets/92786519/4ad9c165-8a96-4c4e-b9cc-0d98a568cfeb">

**Comment by helloitsdamsky** [comment]
seems ok @vikiival can anybody else test?

**Comment by prury** [comment]
> seems ok @vikiival can anybody else test?

working!
![image](https://github.com/kodadot/workers/assets/36627808/060593cb-4660-43e9-be24-32f32672f52d)
