### ISSUE TITLE
OG image card quick tweek for twitter

### ISSUE THREAD

**Issue by yangwao** [kodadot/workers#197]
cc @roiLeo I heard you can pull some CSS tricks to avoid twitter URL in og image cards

![image](https://github.com/kodadot/nft-gallery/assets/5887929/8266e17a-963b-4de8-850d-459b8eb7772b)

**Comment by roiLeo** [comment]
Increased padding

![Screenshot 2023-11-14 at 10-34-11 OpenGraph - Preview Social Media Share and Generate Metatags](https://github.com/kodadot/workers/assets/9987732/3da737e8-ca08-4239-8f53-9bc40820a896)
