### ISSUE TITLE
Subdomain for workers

### ISSUE THREAD

**Issue by vikiival** [kodadot/workers#21]
We can have subdomain for workers so our urls can be shorter.
I will leave this to GPTWao

![Screenshot 2023-01-07 at 16 29 12](https://user-images.githubusercontent.com/22471030/211158353-b40ae513-579a-4555-9aa7-35fba8be4d41.png)

**Comment by yangwao** [comment]
image.w.kodadot.xyz
image-beta.w.kodadot.xyz
ssr-opengraph.w.kodadot.xyz
ssr-opengraph-beta.w.kodadot.xyz

and so on
