### ISSUE TITLE
OG image does not work for drop page

### ISSUE THREAD

**Issue by Jarsen136** [kodadot/workers#215]
After merging #213 and deploy, there are still no changes for the og image. Maybe cache?
<img width="290" alt="image" src="https://github.com/kodadot/workers/assets/31397967/f19d4cd5-e5ce-4f8e-856d-05a113f1bafa">

The preview image works well by the way:
https://workers-ogi.pages.dev/ahp/drops/swirls/__og_image__/og.png

<img width="1216" alt="image" src="https://github.com/kodadot/workers/assets/31397967/8366c812-5cca-452f-8bbb-2560d4244eca">

**Comment by vikiival** [comment]
99% chance that it's cache, may @preschian can confirm

**Comment by Jarsen136** [comment]
> 
> can cleanup snek routes I guess?

Yes I bet

**Comment by roiLeo** [comment]
<img width="428" alt="Capture d’écran 2023-12-04 à 3 59 47 PM" src="https://github.com/kodadot/workers/assets/9987732/4e891869-11bb-4bb0-a700-be93427dffb4">

might need regex to parse/remove markdown description

**Comment by Jarsen136** [comment]
> <img alt="Capture d’écran 2023-12-04 à 3 59 47 PM" width="428" src="https://private-user-images.githubusercontent.com/9987732/287738860-4e891869-11bb-4bb0-a700-be93427dffb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MDI1NTEsIm5iZiI6MTcwMTcwMjI1MSwicGF0aCI6Ii85OTg3NzMyLzI4NzczODg2MC00ZTg5MTg2OS0xMWJiLTRiYjAtYTcwMC1iZTkzNDI3ZGZmYjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDRUMTUwNDExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjZlNGZkZWU5ZWUzMWRhYjE1YjllMWJmZDJkYWYxNGU5YjMzZTQyODM5Y2MxYTU4MDc2ZGI3Y2Q1ZjllZjc3OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OHn4MU9GFDPd5vPA8HYyMDo2Xa2Wp1fo8alGwFa_wK8">
> might need regex to parse/remove markdown description

Is it the same as this issue? https://github.com/kodadot/workers/issues/209
