### ISSUE TITLE
Remove "beta" from preview

### ISSUE THREAD

**Issue by JustLuuuu** [kodadot/workers#237]
I saw this post today: https://x.com/rubenzmart/status/1739277351807304037?s=46&t=lpQMwoVW7c84SvL5Yz5kuQ

![image](https://github.com/kodadot/nft-gallery/assets/104380776/0c02ccb8-5e0f-4ae6-9320-2dfcaf910201)

Can we pls remove [beta] sign from it? I guess also AHP collections have beta in them.

Thx

**Comment by roiLeo** [comment]
![Screenshot 2023-12-25 at 19-14-01 OpenGraph - Preview Social Media Share and Generate Metatags](https://github.com/kodadot/workers/assets/9987732/9fddd43d-19d2-428f-af54-eaf2fd2261d8)
