### ISSUE TITLE
CORS and images not loading

### ISSUE THREAD

**Issue by prury** [kodadot/workers#245]
images not loading(top collections on landing)
![image](https://github.com/kodadot/workers/assets/36627808/9e7dfcdd-9ecf-4ad0-9dac-1e4426fd8d14)

some CORS:

![image](https://github.com/kodadot/workers/assets/36627808/32c9a043-fce3-463e-abcb-fbe8b92fa3a9)

**Comment by preschian** [comment]
looks good on my end

<img width="2032" alt="image" src="https://github.com/kodadot/workers/assets/734428/51748129-c4bf-446d-8f26-348c3cd74624">

<img width="2032" alt="image" src="https://github.com/kodadot/workers/assets/734428/cdf0105d-6bdd-4374-b0bb-4dd44a24f834">

**Comment by preschian** [comment]
Is it probably related to the local network provider to the CF network?

**Comment by prury** [comment]
> Is it probably related to the local network provider to the CF network?

seems normal to me today @preschian, i think it can be closed

**Comment by preschian** [comment]
let's reopen if you face this issue again
