### ISSUE TITLE
Previews does not work on Farcaster app

### ISSUE THREAD

**Issue by vikiival** [kodadot/workers#260]
## Context

As our marketing team is posting links to the farcaster app, it would be nice not to have a broken previews

<img width="606" alt="image" src="https://github.com/kodadot/ops-internal/assets/92786519/abd83e8b-e6e5-4080-92a5-1ad7b3afdf04">

cc @Jarsen136 @preschian as both worked on `ogi` worker

## Ref

- https://github.com/kodadot/ops-internal/issues/1495

**Comment by yangwao** [comment]
It's something else as OG cards works normally
- https://www.opengraph.xyz/url/https%3A%2F%2Fkodadot.xyz%2Fahp%2Fdrops%2Fsplit

Rather integrate Frame for drops would make most sense as Drakula already do that default with their links on FC

- https://github.com/kodadot/nft-gallery/issues/9839

**Comment by preschian** [comment]
checking

**Comment by iamonuwa** [comment]
https://warpcast.com/iamonuwa/0xbabb1801

**Comment by iamonuwa** [comment]
https://42087ab46f0823e6.ngrok.app/ahp/frames/112
