### ISSUE TITLE
Deploy farcaster frame worker 

### ISSUE THREAD

**Issue by yangwao** [kodadot/workers#268]
no rush, we are already have one working from Complexlity so using then one hopefully won't put it down upcoming month, jk I believe next week we will have it up :)

_Originally posted by @yangwao in https://github.com/kodadot/workers/issues/265#issuecomment-2025047568_

**Comment by yangwao** [comment]
can you please deploy our frame?

**Comment by yangwao** [comment]
bummer

https://warpcast.com/yangwao/0x65a7834a

used https://frame.kodadot.workers.dev/gallery/ahp/115

<img width="607" alt="image" src="https://github.com/kodadot/workers/assets/5887929/f1405793-dc67-4dde-b14b-dd412fe9533c">

**Comment by Complexlity** [comment]
Hey man. It does work for me 

![image](https://github.com/kodadot/workers/assets/105590967/02437773-da88-4d86-b715-4b8850d6ae5a)

Probably something to do with the deployment. Use this link instead:

https://kodadot-collections.complexlity.workers.dev/gallery/ahp/115

**Comment by Complexlity** [comment]
**Update**: I found out why. The code assumes the art would have chronological numbering (1 - max-supply). But checking that item on kodadot, it does not.

![image](https://github.com/kodadot/workers/assets/105590967/6b56df24-672e-4294-87dd-94fafc7bb539)
**Fig**: Art used for testing that follows the number system from 1 to max supply

![image](https://github.com/kodadot/workers/assets/105590967/f28f7395-e54e-4be5-9086-787da46dc9c6)
**Fig**: Art you're trying to get. The number is off.

I'm not super experienced with the kodadot queries but I'm sure there's a way to get the items contained in a collection (without passing an item id). Surely that's what the frontend uses.
Maybe @vikiival can help with the query?

**Comment by vikiival** [comment]
> The number is off.

You are completely correct. 

> Maybe @vikiival can help with the query?

Best I could help now

```ts
export async function getItemByOffset(chain: string, collection: string, offset: string | number) {
  const client = getClient(chain as any)
  const query = client.itemListByCollectionId(collection, {
    limit: 1,
    offset: Number(offset),
    orderBy: 'createdAt_ASC',
  })

  console.log(query)

  try {
    const result = await client.fetch<any>(query)
    return result.data?.items
  } catch (error) {
    console.error(error)
    return null
  }
}
```

**Comment by Complexlity** [comment]
> > The number is off.
> 
> You are completely correct.
> 
> > Maybe @vikiival can help with the query?
> 
> Best I could help now
> 
> ```ts
> export async function getItemByOffset(chain: string, collection: string, offset: string | number) {
>   const client = getClient(chain as any)
>   const query = client.itemListByCollectionId(collection, {
>     limit: 1,
>     offset: Number(offset),
>     orderBy: 'createdAt_ASC',
>   })
> 
>   console.log(query)
> 
>   try {
>     const result = await client.fetch<any>(query)
>     return result.data?.items
>   } catch (error) {
>     console.error(error)
>     return null
>   }
> }
> ```

Thanks. I solved it a different way (by fetching all the items). This looks more efficient (for a collection with to many item. I'll test and add it in

**Comment by vikiival** [comment]
> by fetching all the items

Please do not use this

**Comment by Complexlity** [comment]
Here:
https://github.com/kodadot/workers/pull/271

I used the one you made. It should work well now

Test deployment here @yangwao :
https://kodadot-collections.complexlity.workers.dev/gallery/ahp/115

**Comment by yangwao** [comment]
> Test deployment here @yangwao :

Yes, the testing works well. Thank you! 

<img width="184" alt="image" src="https://github.com/kodadot/workers/assets/5887929/4fb97d68-52ee-4597-b61d-b3683973ca1b">

seems view button doesn't work as numbering has changed too 

<img width="350" alt="image" src="https://github.com/kodadot/workers/assets/5887929/dd847f9c-251f-4bf9-a4d7-43cd60546030">

can do in separate issue to not confuse in this one.
