### ISSUE TITLE
Reflect new numbering in frame View button

### ISSUE THREAD

**Issue by yangwao** [kodadot/workers#272]
> Test deployment here @yangwao :

Yes, the testing works well. Thank you! 

<img width="184" alt="image" src="https://github.com/kodadot/workers/assets/5887929/4fb97d68-52ee-4597-b61d-b3683973ca1b">

seems view button doesn't work as numbering has changed too 

<img width="350" alt="image" src="https://github.com/kodadot/workers/assets/5887929/dd847f9c-251f-4bf9-a4d7-43cd60546030">

cc @Complexlity 

and drop the DOT address payment link -> https://kodadot.xyz/dot/transfer or I can do usdc but it will take while

_Originally posted by @yangwao in https://github.com/kodadot/workers/issues/268#issuecomment-2041079357_

**Comment by Complexlity** [comment]
#273. Missed that.

Oh cool. Will do so

**Comment by Complexlity** [comment]
Here: https://kodadot.xyz/dot/transfer?target=129A7hHnzWy8XfLrxBTdwRchhdp84zVXPKp6LBaMfYLM2oXZ&amount=

cc: @yangwao

**Comment by yangwao** [comment]
> Here: [kodadot.xyz/dot/transfer?target=129A7hHnzWy8XfLrxBTdwRchhdp84zVXPKp6LBaMfYLM2oXZ&amount=](https://kodadot.xyz/dot/transfer?target=129A7hHnzWy8XfLrxBTdwRchhdp84zVXPKp6LBaMfYLM2oXZ&amount=)

https://polkadot.subscan.io/extrinsic/0xb61009330a29f6ef8b30cb72d14a3d08e87053b73ba4f09533ec0452129bea79
