### ISSUE TITLE
R2(IPFS) worker

### ISSUE THREAD

**Issue by vikiival** [kodadot/workers#304]
### Context 

[nft.storage has end of life in 30/06/204](https://nft.storage/blog/important-product-updates-nft-storage-is-evolving) therefore [nft-storage worker wont work](https://github.com/kodadot/workers/tree/main/nft-storage).

Therefore as I was speaking on last dev call we need a replacement for it :)

### Task

1. Create new worker called `ipos` (stands for inter-planetary object storage)
2. make same API as `nft-storage` worker (`/pinJson`, `/pinFile`)
3. the content should be uploaded to R2 under the "created" CID
4. Ideally if same response is used

### Tech stack 

Hono + R2 + (aaand maybe KV?)

Library wise you would probably need https://github.com/alanshaw/ipfs-only-hash
**or**
https://github.com/ipfs/js-ipfs-unixfs/tree/main/packages/ipfs-unixfs-importer

with 
- https://github.com/ipfs/js-stores/tree/main/packages/datastore-s3
- or https://github.com/ipfs/js-stores/tree/main/packages/blockstore-s3

### Routes

![Screenshot 2024-06-14 at 15 50 57](https://github.com/kodadot/workers/assets/22471030/45278daa-82bd-4119-9f11-8a31fa42ee78)

![Screenshot 2024-06-14 at 15 51 05](https://github.com/kodadot/workers/assets/22471030/0f82008e-9ddc-4f37-800e-990f08a3a294)

![Screenshot 2024-06-14 at 15 51 11](https://github.com/kodadot/workers/assets/22471030/167fd1d5-fdfc-47f4-8c47-541e372b301f)

**Comment by vikiival** [comment]
https://www.youtube.com/watch?v=q5bKjuu3kdE

**Comment by vikiival** [comment]
I realized that this issue was already well described. 

So the task:
Using the same api 
Pin content to filebase
Response from pin contains CID. 
with this data put content to R2.

**Comment by preschian** [comment]
> Pin content to filebase
> Response from pin contains CID.
> with this data put content to R2.

nice 👍🏻
This is what I was thinking too

make sure using same r2 bucket with image-workers. ref: https://github.com/kodadot/workers/blob/21fb3d7f7e74ff00fe50c1fb1022f08c5d24fba9/services/image/wrangler.toml#L50-L53
