### ISSUE TITLE
Revert nftstorage redirect on image 

### ISSUE THREAD

**Issue by vikiival** [kodadot/workers#311]
## Context

Seems like this (- https://github.com/kodadot/workers/pull/298) redirect causes indexer to stop.
I tried to use different GW in - #310 but I did not have success
Only usable option was revert image prod to older version.

## Task

revert this change

**Comment by preschian** [comment]
im currently afk, can someone revert it. cc @kodadot/internal-dev 

anyway, seems like not related. because that PR deployed more than 2 weeks ago. meanwhile, the indexer stuck just yesterday

**Comment by preschian** [comment]
I'm still commuting, eta in 1 hour

**Comment by vikiival** [comment]
> anyway, seems like not related. because that PR deployed more than 2 weeks ago. meanwhile, the indexer stuck just yesterday

Soo when you make your wife angry two weeks ago it does not mean that you would not make you angry today.

**Comment by preschian** [comment]
it should stuck between 2 weeks range right?
