### ISSUE TITLE
Update CORS rules

### ISSUE THREAD

**Issue by vikiival** [kodadot/workers#315]
https://beta.kodaart-production.pages.dev

![Screenshot 2024-07-08 at 10 46 17](https://github.com/kodadot/workers/assets/22471030/956bac1c-faea-4df8-b5d1-1f2dc2bd8198)

**Comment by vikiival** [comment]
Cc @preschian

**Comment by preschian** [comment]
> [beta.kodaart-production.pages.dev](https://beta.kodaart-production.pages.dev)

oh, I just realized, this is for beta deployment righ? I just assign beta.koda.art to beta.kodaart-production.pages.dev. no need to update cors url
