### ISSUE TITLE
feat(price): add additional token price fallbacks  

### ISSUE THREAD

**Issue by hassnian** [kodadot/workers#325]
kraken's API is returning 0 as `MNT`'s price 

I see that currently we have `coingecko` as a fallback in the frontend

Is there any reason why we don't have `coingecko`  in the worker side? 

cc @preschian 

---------

edit: 

worker map is missing MNT

![CleanShot 2024-08-08 at 12 40 59@2x](https://github.com/user-attachments/assets/1cc046b3-c2c7-4d38-8fb4-5a3c895dd96f)

https://api.kraken.com/0/public/Ticker?pair=MNTUSD

<img src="https://github.com/user-attachments/assets/65a25ff3-5510-4317-bc1f-330c0c929297" width="400" />

**Comment by preschian** [comment]
> Is there any reason why we don't have `coingecko` in the worker side?

at that time we face some issue: https://github.com/kodadot/workers/pull/195#issuecomment-1808039302

feel free to test it again with coingecko

**Comment by preschian** [comment]
> > Is there any reason why we don't have `coingecko` in the worker side?
> 
> at that time we face some issue: [#195 (comment)](https://github.com/kodadot/workers/pull/195#issuecomment-1808039302)
> 
> feel free to test it again with coingecko

probably I didn't implement it correctly
