### ISSUE TITLE
Revalidate image-workers cache

### ISSUE THREAD

**Issue by preschian** [kodadot/workers#38]
add `DELETE` request to image-workers endpoint. to revalidate the cache

update: it's working again

![Screenshot 2023-03-08 172442](https://user-images.githubusercontent.com/734428/223688649-7c66b4ca-843a-41b7-b1f3-f57c094cb59f.png)
![Screenshot 2023-03-08 172249](https://user-images.githubusercontent.com/734428/223688658-349942ba-d526-4576-9694-9b40a9cf743c.png)

**Comment by vikiival** [comment]
> update: it's working again

so close?

**Comment by vikiival** [comment]
Btw have you seen?
- https://github.com/kodadot/snek/pull/157
