### ISSUE TITLE
SubQuery Webhook

### ISSUE THREAD

**Issue by vikiival** [kodadot/workers#4]
Simple CF worker that takes SQ json and pass it to the discord webhook

```json
{
    "type": "height",
    "text": "[<https://explorer.subquery.network/subquery/bighammerw/testalertproduct?stage=false%7Cbighammerw/testalertproduct> (Production slot)] the processingBlockHeight of indexer node stop growing in the last 15 minutes"
}
```

**Comment by yangwao** [comment]
I guess it's should be matter of provider support conversion through parameter

Like gh webhooks to discord works you add parameter and it do transformation, no need to run service for this as adds unnecessary overhead

**Comment by vikiival** [comment]
Closing since we dont use SubQuery anymore
