### ISSUE TITLE
`ssr-opengraph` - rmrk2

### ISSUE THREAD

**Issue by preschian** [kodadot/workers#44]

**Comment by yangwao** [comment]
hmm 
- https://socialcards.dev/

**Comment by yangwao** [comment]
- https://github.com/kodadot/nft-gallery/issues/5567

**Comment by yangwao** [comment]
> * prerender.io

trying hobby plan?



> * headless-render-api.com

Maybe this one if so? 
![image](https://user-images.githubusercontent.com/5887929/230794513-5e74b172-010d-4a21-9678-e0d47117a0c9.png)

> ssr-opengraph

I guess this would be best?

**Comment by yangwao** [comment]
Let's go with `ssr-opengraph`

**Comment by yangwao** [comment]
so what's the blocker on these @preschian ?

**Comment by vikiival** [comment]
released #5669

**Comment by vikiival** [comment]
<img width="360" alt="Screenshot 2023-04-14 at 21 03 34" src="https://user-images.githubusercontent.com/22471030/232133917-1296af2c-db70-4710-a67f-fd65faf4c9f6.png">

**Comment by yangwao** [comment]
related
- https://github.com/kodadot/workers/pull/70

**Comment by yangwao** [comment]
- https://github.com/kodadot/workers/actions/runs/4713419090 deployed `ssr-opengraph-beta` 

btw, if these triggers would be 

`*.kodadot.xyz/ksm/*` would not work or it would throw errors on some other routes than `u`,`collection`,`gallery` ?

![image](https://user-images.githubusercontent.com/5887929/232313028-e63d8d52-e381-44e2-a59d-968a5cea9a21.png)

**Comment by yangwao** [comment]
- some of rmrk2 nft will fallback to the default image, because of a different schema. related: https://github.com/kodadot/uniquery/issues/25

**Comment by yangwao** [comment]
huh related @preschian ?

can't open in incognito https://canary.kodadot.xyz/ksm/collection/3e6f301b0a0b1a0e4e-MRWH/

![image](https://user-images.githubusercontent.com/5887929/232314351-957cec4b-be1a-4660-9ed4-6c2e0ef3874f.png)
