### ISSUE TITLE
Rework image gateway

### ISSUE THREAD

**Issue by vikiival** [kodadot/workers#53]
Current state is that the image gateway is ultra slow. What I propose is:

## Image Worker:

- Check CF Images
- Check R2 
If one is present cache the response and return
Else:
 - spawn Upload worker (and do not wait for it).
 - return redirect to kodadot ipfs infura

## Upload Worker:
- Get response from IPFS (promise any as done on image currently)
If it's image - push to CF Images
Else push to R2

@preschian wdyt?

**Comment by preschian** [comment]
lets continue here https://github.com/kodadot/workers/issues/132
