### ISSUE TITLE
image-worker domain certificate inactive

### ISSUE THREAD

**Issue by preschian** [kodadot/workers#57]
does anyone know why the image-worker domain is inactive? @yangwao @vikiival 

| image-beta | image | compared to my testing domain |
| --- | --- | --- |
| ![image](https://user-images.githubusercontent.com/734428/229693157-f5650589-b52b-46ef-9c16-1ff3bc2b8491.png) | ![image](https://user-images.githubusercontent.com/734428/229693272-c1013d85-1166-4f7f-8d57-b81f56d68aa3.png) | ![image](https://user-images.githubusercontent.com/734428/229693317-06796f27-376f-462b-905b-5354310854f5.png) |

**Comment by vikiival** [comment]
In the meantime please use `image-beta.kodadot.workers.dev`

**Comment by yangwao** [comment]
i was not touching anything but looks like cf glitch? by these certs are ok 🥰

![Screenshot_20230404_125855_Chrome.jpg](https://user-images.githubusercontent.com/5887929/229771627-7728c582-a7c0-4a41-aa18-9af97e69ad8d.jpg)

**Comment by yangwao** [comment]
but seems assets loads for me well  

https://image.w.kodadot.xyz/ipfs/bafybeibblf24qqngkfos4j3xpb33kffgqyeucdrcn4z2sn7o5mikwx7itu

**Comment by yangwao** [comment]
I would keep it as for later investigation, it's definitely suspicious, I can read domain on desktop later

**Comment by yangwao** [comment]
initialization of new one took around <3 min of new cert so, lil bit downtime 👀

**Comment by yangwao** [comment]
oh I guess it's something CF could not renew certs? 👀 sense some subdomain issues

**Comment by yangwao** [comment]
readded, plus added backup in case we will be hot-switching or so :)

![image](https://user-images.githubusercontent.com/5887929/230060428-50bbde0a-c532-483f-83f2-db3db5d41692.png)

![image](https://user-images.githubusercontent.com/5887929/230060639-9ccba216-f505-4d9e-adfe-270ee3f1be59.png)
