### ISSUE TITLE
missing IMAGE_API_TOKEN for image-beta

### ISSUE THREAD

**Issue by preschian** [kodadot/workers#58]
unable to upload the image to cf-images, error 400

no IMAGE_API_TOKEN on image-beta. cc @yangwao @vikiival 

![image](https://user-images.githubusercontent.com/734428/229699755-20e9b9cf-ff90-41fe-9f8c-d59bfe5372ab.png)

```json
{
  "message": [
    "https://wsrv.nl/?url=https%3A%2F%2Fr2.infura-ipfs.io%2Fipfs%2FQmcsepH551FpiqdeyKbsMC5Md78QYzKQLY52H6ExTvdwKM&w=1400"
  ],
  "level": "log",
  "timestamp": 1680586987868
},
{
  "message": [
    "uploadStatus",
    400
  ],
  "level": "log",
  "timestamp": 1680586791587
}
```

**Comment by vikiival** [comment]
@preschian try secret `CLOUDFLARE_IMAGE_API_TOKEN`

https://github.com/kodadot/workers/blob/868a4f0ea1d7375d7899aaa8a044030ee70fd01e/direct-upload/src/lib.rs#L68

**Comment by vikiival** [comment]
```
🌀 Creating the secret for the Worker "image-beta"
✨ Success! Uploaded secret IMAGE_API_TOKEN
```
