### ISSUE TITLE
Replicate has changed API 

### ISSUE THREAD

**Issue by yangwao** [kodadot/workers#59]
![image](https://user-images.githubusercontent.com/5887929/230411060-972da187-0876-438d-bff6-43d5d85558bc.png)

![image](https://user-images.githubusercontent.com/5887929/230411113-e9fbe2f1-eca8-4e10-99cc-491100132242.png)

**Comment by yangwao** [comment]
and I guess it's good make it way we can reuse it in mass-mint somehow 👀

**Comment by vikiival** [comment]
Total Upload: 573.33 KiB / gzip: 246.93 KiB
Uploaded replicate (3.78 sec)
Published replicate (1.44 sec)
