### ISSUE TITLE
missing `*.kodadot.xyz/:prefix/detail/*"`? for ssr-opengraph

### ISSUE THREAD

**Issue by preschian** [kodadot/workers#75]
missing `*.kodadot.xyz/:prefix/detail/*"`?

_Originally posted by @roiLeo in https://github.com/kodadot/workers/pull/74#pullrequestreview-1387577718_

**Comment by vikiival** [comment]
looks like it works

![Screenshot 2023-04-17 at 13 00 55](https://user-images.githubusercontent.com/22471030/232465827-cbf62c66-dc26-497e-bb7b-e71160a06ef1.png)

**Comment by roiLeo** [comment]
IMO this is more for legacy purposes as some links have already been shared with this type of url
