### ISSUE TITLE
simplify ssr-opengraph routes

### ISSUE THREAD

**Issue by preschian** [kodadot/workers#79]
- https://github.com/kodadot/workers/actions/runs/4713419090 deployed `ssr-opengraph-beta` 

btw, if these triggers would be 

`*.kodadot.xyz/ksm/*` would not work or it would throw errors on some other routes than `u`,`collection`,`gallery` ? Just thinking simplifying it per-chain

![image](https://user-images.githubusercontent.com/5887929/232313028-e63d8d52-e381-44e2-a59d-968a5cea9a21.png)

_Originally posted by @yangwao in https://github.com/kodadot/workers/issues/44#issuecomment-1510375069_

**Comment by yangwao** [comment]
😍

**Comment by roiLeo** [comment]
can't we do something like `*.kodadot.xyz/*/gallery/*` ?

**Comment by preschian** [comment]
> can't we do something like `*.kodadot.xyz/*/gallery/*` ?

maybe it's possible. we can try that

btw, can we fix this first? https://github.com/kodadot/workers/issues/88 cc @yangwao
