### ISSUE TITLE
ssr-opengraph not works on kodadot.xyz

### ISSUE THREAD

**Issue by preschian** [kodadot/workers#88]
right now ssr-opengraph does not work on kodadot.xyz. already tried it with redeploy but still didn't work ref: https://github.com/kodadot/workers/pull/86#issuecomment-1543322781

- kodadot.xyz (not working at all). ref: https://www.opengraph.xyz/url/https%3A%2F%2Fkodadot.xyz%2Frmrk%2Fgallery%2F8720634-66fae573cab828190c-KNRY-KANARY_110-0000000000000110
- beta.kodadot.xyz (works). ref: https://www.opengraph.xyz/url/https%3A%2F%2Fbeta.kodadot.xyz%2Frmrk%2Fgallery%2F8720634-66fae573cab828190c-KNRY-KANARY_110-0000000000000110
- canary.kodadot.xyz (works). ref: https://www.opengraph.xyz/url/https%3A%2F%2Fcanary.kodadot.xyz%2Frmrk%2Fgallery%2F8720634-66fae573cab828190c-KNRY-KANARY_110-0000000000000110

@yangwao @vikiival @roiLeo  maybe need to contact Cloudflare support? need to ask them why it doesn't work at `kodadot.xyz` only

I already tested it in my domain, and it works. deployed the same code. the only changes I made were only on wrangler.toml to change from `kodadot.xyz` to `preschian.xyz`

**Comment by preschian** [comment]
just found out that the request dropped to 0 from last night (based on my local time)

![image](https://github.com/kodadot/workers/assets/734428/26b823cd-bd7a-4ecd-b817-24c1bc49aeb0)

cpu time:

![image](https://github.com/kodadot/workers/assets/734428/12ecdc40-38f6-4e10-be09-784b165758cd)

duration:

![image](https://github.com/kodadot/workers/assets/734428/46920a57-4a4e-4a6d-a002-78989168e003)

**Comment by preschian** [comment]
are there any changes at that time? maybe DNS configuration or something?

**Comment by roiLeo** [comment]
maybe related with https://github.com/kodadot/nft-gallery/issues/5887#issuecomment-1542528827?

**Comment by yangwao** [comment]
> are there any changes at that time? maybe DNS configuration or something?

there was combined outage yesterday with CF API and other their services and Github, so deadly combo if it was something deployed but opengraph was untouched IIRC

mm I noticed that it was serving me half bundle from old and some from new stuff so deploy was pretty mixed yesterday, pitty day to deploy tbh and release rmrk2.. 

I've enabled proxied serving, maybe be it fixed now?
rmrk2.kodadot.xyz is unproxied
nft.kodadot.xyz unproxied
kodadot.xyz is proxied

**Comment by yangwao** [comment]
Tried redeploy recent production with proxied but even after 10 minutes it's still serving 2 days old kodadot with only BSX and RMRKv1 so I've turned back to unproxied to have at least working rmrk2 and we can figure out those cards other day.

Still curious what's different against beta as it's deployed through CF-pages, could be how CNAME is being flatten, edge caching is triggered to invalid cache or something I like that I sense

**Comment by preschian** [comment]
> Tried redeploy recent production with proxied but even after 10 minutes it's still serving 2 days old kodadot with only BSX and RMRKv1

interesting, seems like the fix should enable proxied

this is on my domain ![image](https://github.com/kodadot/workers/assets/734428/a065b1dc-fa17-4813-b4eb-7c827de26313)

**Comment by yangwao** [comment]
I can give shot enabled proxied again?

**Comment by yangwao** [comment]
![image](https://github.com/kodadot/workers/assets/5887929/17b0209d-4531-4b7a-b06c-ac6749aa88f8)

we are so back

purged cache everywhere

![image](https://github.com/kodadot/workers/assets/5887929/4d9a39ff-547b-4940-b661-5b073799d876)

I think we hit some CF edge case... or their broken CDN where is new builds not pushed or so

**Comment by yangwao** [comment]
trying bit radical solution 

![image](https://github.com/kodadot/workers/assets/5887929/a193c77f-cdc6-4564-b587-02053d423e32)

**Comment by yangwao** [comment]
ok, apparently CF container for pages was untouched and dead,.... seems we are so back 

![image](https://github.com/kodadot/workers/assets/5887929/55fe68ef-cf2d-4d02-88a3-b26ed54f90cb)

@preschian we can continue on this?

**Comment by preschian** [comment]
> ok, apparently CF container for pages was untouched and dead,.... seems we are so back
> 
> 
> @preschian we can continue on this?

yeay, it works right now
![image](https://github.com/kodadot/workers/assets/734428/25068eff-40d7-4769-9851-b783ecf163e5)

**Comment by yangwao** [comment]
So can be this closed now @preschian ?

**Comment by preschian** [comment]
> So can be this closed now @preschian ?

yes2, now we can continue to this https://github.com/kodadot/nft-gallery/issues/6284

**Comment by yangwao** [comment]
<img src="https://media2.giphy.com/media/b85mPT4Usz7fq/giphy.gif"/>
