### ISSUE TITLE
unify nft item metadata

### ISSUE THREAD

**Issue by preschian** [kodadot/workers#95]
this is a kinda temporary fix. for the first time load is still slow to load, because of processing mp4 video. video size on `/stmn/gallery/18-1` is around 34MB

I think it's better to unify some fields and add mime-type from the indexer side. on `rmrk v1`, the `image` field is only for static images, and all animated media are on the `animation_url` field. on the other chain, the `image` field can be any format

I found that on `rmrk v1`, `meta.type` is for the mime type only. but, on `rmrk v2` it can be anything. example:

<table>
<tr>
    <th>rmrk v1</th>
    <th>rmrk v2</th>
</tr>

<tr>
<td>
<pre>{
  "id": "7522506-900D19DC7D3C444E4C-AIW-AI_WOMAN-0000000000000001",
  "name": "AI woman",
  "meta": {
    "id": "ipfs://ipfs/QmVRPTEtZ7pwShvNYTxyPTE7XDzEPpwYunPhr23RFBw5aY",
    "type": "video/mp4"
  }
}
</pre>
</td>

<td>
<pre>{
  "id": "14336459-560189524f21b73a25-AXECOLLECTION2-MARKER-00002579",
  "name": "Marker of Endlessness",
  "meta": {
    "id": "ipfs://ipfs/bafybeifwsdvejxy45zzuuyyoey4wov3ftyj3ak6f7yrdqremr5apbs2474/metadata.json",
    "type": "Marker"
  }
}
</pre>
</td>
</tr>
</table>

ref: https://github.com/kodadot/nft-gallery/pull/6080#issuecomment-1558689637

**Comment by vikiival** [comment]
> I think it's better to unify some fields and add mime-type from the indexer side. on `rmrk v1`, the `image` field is only for static images, and all animated media are on the `animation_url` field. on the other chain, the `image` field can be any format

Sure, does it happen also on stmn and snek? 

for rmrk2 we neee to find alternative as this was mainly processed by rmrk-team

**Comment by vikiival** [comment]
Ссс @preschian
